CIR-748-Updated Are you an agent text.
hmrc/interest-restriction-return-frontend pull request #201
Opened 2020-12-09 16:02 UTC by AdamCoops

2020-12-09 16:12 UTC, DevAndyroo requested changes

2020-12-09 16:12 UTC, DevAndyroo commented on conf/messages.en
> +agentActingOnBehalfOfCompany.subheading = About the return
Is this line needed?

2020-12-09 16:35 UTC, burns238 commented on conf/messages.en
> +agentActingOnBehalfOfCompany.subheading = About the return
I assume it's the section sub heading if you look at the ticket: https://jira.tools.tax.service.gov.uk/browse/CIR-748

But then I'd have expected us to have replaced that "Agents" string?

2020-12-10 10:16 UTC, DevAndyroo approved these changes

2020-12-10 10:18 UTC, DevAndyroo commented on conf/messages.en
> +agentActingOnBehalfOfCompany.subheading = About the return
https://github.com/hmrc/interest-restriction-return-frontend/pull/201/files#diff-f069a65c418e85f16d9363b96a73254b4d0c65c9947bcc76b12f73455632bc54R41 yeah, this line specifically, I think already should have the "About the return" covered

2020-12-10 10:21 UTC, merged