CIR-771-Updated the content for UTR
hmrc/interest-restriction-return-frontend pull request #212
Opened 2020-12-15 11:01 UTC by AdamCoops

2020-12-15 16:54 UTC, versatil56 requested changes

2020-12-15 16:54 UTC, versatil56 commented on app/views/aboutReturn/ReportingCompanyCTUTRView.scala.html
> +            label = "reportingCompanyCTUTR.heading",
this should point to its label in `messages.en`

2020-12-16 09:14 UTC, AdamCoops commented on app/views/aboutReturn/ReportingCompanyCTUTRView.scala.html
> +            label = "reportingCompanyCTUTR.heading",
Given we're using this as a label and not a heading I'd figured it was best to do it this way around. I'll swap it back.

2020-12-16 12:24 UTC, DevAndyroo approved these changes

2020-12-16 13:08 UTC, merged