CIR-848-Updated the Contents for Check your answer
hmrc/interest-restriction-return-frontend pull request #214
Opened 2020-12-16 14:41 UTC by AdamCoops

2020-12-16 15:03 UTC, DevAndyroo commented on test/assets/messages/CheckAnswersGroupLevelInformationMessages.scala
> +  val revisingReturn = "Revised return"
Was this one that was meant to be changed, I got the impression the changed that was done here was to "change it back"?

2020-12-16 15:11 UTC, DevAndyroo requested changes

2020-12-16 15:11 UTC, DevAndyroo commented on test/assets/messages/CheckAnswersGroupLevelInformationMessages.scala
> +  val revisingReturn = "Revised return"
After discussing with @burns238 seems that this change is right, but this variable might have moved at somepoint from grouplevelinfo to about return, but not this constant in test @AdamCoops is it possible for you to move it to where it's used rather than where it currently exists to avoid confusion?

2020-12-17 09:18 UTC, AdamCoops commented on test/assets/messages/CheckAnswersGroupLevelInformationMessages.scala
> +  val revisingReturn = "Revised return"
This change matches the story v2 to v3 request change. 
I'll have a look at moving it as well now.

2020-12-17 09:56 UTC, DevAndyroo approved these changes

2020-12-17 16:00 UTC, merged