CIR-752 - Revision Information
hmrc/interest-restriction-return-frontend pull request #216
Opened 2020-12-16 16:58 UTC by burns238

2020-12-16 17:04 UTC, DevAndyroo requested changes
Also, generally, do we need any integration tests for this?

2020-12-16 17:05 UTC, DevAndyroo requested changes

2020-12-16 17:05 UTC, DevAndyroo commented on app/navigation/AboutReturnNavigator.scala
> +      case Some(true) => aboutReturnRoutes.TellUsWhatHasChangedController.onPageLoad(NormalMode) //TODO: Link to Revision Information Page when implemented
Remove the TODO

2020-12-17 09:58 UTC, AdamCoops approved these changes

2020-12-17 13:47 UTC, burns238 commented
> Also, generally, do we need any integration tests for this?

There are integration tests:
- RevisingReturnControllerISpec.scala checks that the previous page passes into this one successfully
- TellUsWhatHasChangedControllerISpec.scala is the integration test for our spec.

Or did we mean a different variety of integration tests?

2020-12-17 13:49 UTC, DevAndyroo approved these changes

2020-12-21 15:02 UTC, merged