Removing current way or checking for data completeness
hmrc/interest-restriction-return-frontend pull request #259
Opened 2021-01-20 15:04 UTC by versatil56

2021-01-20 16:28 UTC, DevAndyroo requested changes
I've only briefly looked over this, will give a proper look tomorrow - might also be good to have a session talking over the changes as well, since it has quite a big impact

2021-01-20 16:28 UTC, DevAndyroo commented on app/controllers/reviewAndComplete/ReviewAndCompleteController.scala
> +    val reviewAndCompleteModel2 = ReviewAndCompleteModel()
I think this can be named better

2021-01-20 17:14 UTC, versatil56 commented on app/controllers/reviewAndComplete/ReviewAndCompleteController.scala
> +    val reviewAndCompleteModel2 = ReviewAndCompleteModel()
whoops! doing it now, all that code is going to go anyway - the page is now receiving an empty model (not working)

2021-01-21 15:01 UTC, DevAndyroo approved these changes

2021-01-21 15:02 UTC, merged