CIR-1338-Implement navigation changes
hmrc/interest-restriction-return-frontend pull request #326
Opened 2021-03-03 16:32 UTC by AdamCoops

2021-03-03 16:37 UTC, burns238 requested changes

2021-03-03 16:37 UTC, burns238 commented on app/navigation/UkCompaniesNavigator.scala
>      }),
This line can simply be:
ConsentingCompanyPage -> ((idx, userAnswers) => routes.CompanyQICElectionController.onPageLoad(idx, NormalMode)),

2021-03-04 15:54 UTC, burns238 approved these changes

2021-03-08 10:58 UTC, versatil56 approved these changes

2021-03-09 09:09 UTC, merged