CIR-1379-Update front end to have dynamic deemed parent wording
hmrc/interest-restriction-return-frontend pull request #332
Opened 2021-03-10 16:13 UTC by AdamCoops

2021-03-11 13:18 UTC, DevAndyroo requested changes

2021-03-11 13:18 UTC, DevAndyroo commented on app/controllers/ultimateParentCompany/ParentCompanyNameController.scala
> +        }
Can we move the duplicated code to a private function?

2021-03-11 14:58 UTC, DevAndyroo approved these changes

2021-03-15 11:26 UTC, burns238 approved these changes

2021-03-15 14:06 UTC, merged